FROM golang:1.26.2 AS ci
WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .
RUN go test ./...

FROM golang:1.26.2 AS build
WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/cafe-cpm ./cmd/cafe-cpm

FROM gcr.io/distroless/base-debian12:nonroot
COPY --from=build /out/cafe-cpm /usr/local/bin/cafe-cpm
EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/cafe-cpm"]
